### ISSUE TITLE
Test: Size (Numeric Systems)

### ISSUE THREAD

**Issue by CSenshi** [CSenshi/Validator#107]
`Size` Rule had enhancements over past few commits, we need to test it better and check how it works with other rules.

Need to test with Number System Rules:
* Integer (test_06)
* Decimal (test_07)
* Binary (test_08)
* Octal (test_09)
* Hex (test_10)

All of the tests can be found in [tests/rules/test_size.py](https://github.com/CSenshi/Validator/blob/master/tests/rules/test_size.py) file

**Comment by Gugatke** [comment]
i'll do it
