### ISSUE TITLE
Test: Size (Collections)

### ISSUE THREAD

**Issue by CSenshi** [CSenshi/Validator#108]
`Size` Rule had enhancements over past few commits, we need to test it better and check how it works with other rules.

Need to test with Collection Rules:
* list (test_11)
* dict (test_12)
* json (test_13)
* String (test_13)

All of the tests can be found in [tests/rules/test_size.py](https://github.com/CSenshi/Validator/blob/master/tests/rules/test_size.py) file

**Comment by tkech17** [comment]
i'll do it
