### ISSUE TITLE
Nested properties validation?

### ISSUE THREAD

**Issue by luminescent** [CSenshi/Validator#121]
Would it be possible to validate more complex requests, with nested properties? 

Eg: 

```
{
	"name": "some name",
	"x": {
		"a": "a_val",
		"b": "b_val"
	}
}
```
And the rules could for example be: 
```
{
	"name": "required",
	"x": {
		"a": "required",
		"b": "mail"
	}
}
```

**Comment by CSenshi** [comment]
Yes, it is feature requested by many and we try to do our best about it. As for now our development is stopped, but it will be continued in a few weeks and we are going to rework code and then implement new features like this one.
