### ISSUE TITLE
Remove Print Statement

### ISSUE THREAD

**Issue by rjbroussard** [CSenshi/Validator#123]
There is a print statement that runs for every custom rule that prints out the function name. I would like that removed as to not bog up logs. 

it can be found at: `validator/rules_src/__init__.py:55`

Thanks!

**Comment by CSenshi** [comment]
I would accept PR if you would like to contribute

**Comment by rjbroussard** [comment]
Sure! I am unfamiliar with the process do you guys user feature branches and then merge them in? I tried pushing a branch but got access denied when pushing with set upstream

**Comment by CSenshi** [comment]
Currently development is stopped but yes, please create separate feature branch after forking and PR with that branch
