### ISSUE TITLE
Not required rule doesnot work

### ISSUE THREAD

**Issue by dzhaugasharov** [CSenshi/Validator#125]
**Bug Description:**
Is there not a required rule?
Im tryin this rule: 
```
params = {'otherParam': 'ABC'}
valid = Validator(params, {
        'mark': 'integer|min:1|max:3'
    })
```
The param mark is not required, so it can be None. But I get this errors:
`{'mark': {'Integer': "Expected Type of Int or Str, Got: <class 'NoneType'>", 'Min': "Could not get size from data. type = <class 'NoneType'>", 'Max': "Could not get size from data. type = <class 'NoneType'>"}}`

**Comment by CSenshi** [comment]
Currently we don't support not required rule, but we are going to implement 'nullable' rule, so it can handle cases like this.

**Comment by dzhaugasharov** [comment]
> Currently we don't support not required rule, but we are going to implement 'nullable' rule, so it can handle cases like this.

That would be awesome. Looking forward to it.

**Comment by CSenshi** [comment]
Thanks, for some time we stopped development of package, but we will be on the rails soon, if you would like to contribute I'd accept PR for this issue
