### ISSUE TITLE
Rules' error handling

### ISSUE THREAD

**Issue by iko1133** [CSenshi/Validator#30]
1) An error occurs when the user enters rules and requests with different keys set.
2) An error occurs when the user enters an empty set of rules for some field(s). 
both of these cases should be handled.

**Comment by mateuszz0000** [comment]
@iko1133, if you haven't started yet, I could take this issue :)

**Comment by iko1133** [comment]
@mateuszz0000 sorry, i have already started working on it :) will probably done today or tomorrow
