### ISSUE TITLE
Array validation

### ISSUE THREAD

**Issue by iko1133** [CSenshi/Validator#31]
Validator needs to validate the array of requests too.

**Comment by mateuszz0000** [comment]
Hello, 

I am thinking about solution and I have 2 ideas for that:

1) Allow passing to Validator's `__init__` two types for request argument (either single request or array). Then we need to validate whether it's array or not.

2) Always passing array. For me it's better option (less checking and consistent types)

Maybe you have better idea for this issue? :smiley:

**Comment by iko1133** [comment]
Hello,
I was thinking the first solution is much better, because it's much more userfriendly, they won't have to create an array just to pass it to the validator, it would not be convenient.

**Comment by mateuszz0000** [comment]
hmm... you are right - it will be more flexible.

```
Validator(Request, rules)
Validator([Request Request], rules) 
```
I can work on it if nobody wants :)

**Comment by iko1133** [comment]
Yes they won't be writing any unnecessary code ^_^
go on, if you want to then :)

**Comment by CSenshi** [comment]
@mateuszz0000 It would be better to validate with other method.

we can create another function in validator.py something like:
```python
def validate_many(requests, rule):
   pass

# usage
validate_many([req1, req2, req3], rule)
```

**Comment by mateuszz0000** [comment]
For now request it's passed in `__init__`.  For above solution will be:
```
Validator(Request, Rules).validate()
# for many
Validator(NONE??, Rules).validate_many(requests)
```
For me it's not clean.

How about something like that:
```
class ValidatorMany(maybe inherit from Validator?):
    def __init__(self, requests, rules):
        ... logic ...

    def validate(self):
        ... logic ...
```

**Comment by CSenshi** [comment]
In the `validator/validator.py` we have one class and one function

```python
class Validator:
    def __init__(self, request, rules):
        ...

    def validate(self):
        ...

    def get_error_messages(self):
        ...
      
    def check_rules(self):
        ...

def validate(req, rules, return_errors=False):
    ...
```

Validator class is responsible for validating one request, so my solution is to create second function like this (without class instance):
```python
def validate_many(req_array, rules, return_errors=False):
    ...
```

You are rigth, we can also create ValidatorMany class, but would it not be overkill? What do you think?

**Comment by mateuszz0000** [comment]
I didn't notice this function: cry: The easiest and most readable solution is to create `validate_many`. I apologize for the misunderstanding .

**Comment by CSenshi** [comment]
No problemo :) Go for it! :100:
