### ISSUE TITLE
between.

### ISSUE THREAD

**Issue by beqakd** [CSenshi/Validator#41]
I think we should change between class as so user can choose min and max separately. I mean if user goes for between(10,12) we all know what it is. But if it goes for between(10,) or between(,12) maybe we should go for min and max ones?

**Comment by CSenshi** [comment]
Reasonable issue. Let's do it but first of all, what solution do you suggest for doing argument passing as (10, ) or (, 12)?

**Comment by beqakd** [comment]
I will suggest one in 24hr.

**Comment by CSenshi** [comment]
Ok, your time is ticking
https://countingdownto.com/?c=3062048

**Comment by beqakd** [comment]
Dude its few minutes late :) :D

**Comment by CSenshi** [comment]
Fixed it. Don't loose your bloody 3 minutes!
