### ISSUE TITLE
New Rule: Same

### ISSUE THREAD

**Issue by CSenshi** [CSenshi/Validator#61]
Write rule that validates data to be exactly same as given value.

Description: "The given field must match the field under validation"

Please see [CONTRIBUTING.md](https://github.com/CSenshi/Validator/blob/master/CONTRIBUTING.md) for Contribution details :100:

**Comment by bsoyka** [comment]
Going to take this one on too.

**Comment by CSenshi** [comment]
NOTE:
check() takes argument that represents other field name in the same dictionary :

Example:
```python3
req = {"old_pass": "secret", "new_pass": "secret"}
rule = {"new_pass": "same:old_pass"}
validate(req, rule)  # True

req = {"old_pass": "old_secret", "new_pass": "new_secret"}
rule = {"new_pass": "same:old_pass"}
validate(req, rule)  # False
```
