### ISSUE TITLE
New Rule: Accepted

### ISSUE THREAD

**Issue by CSenshi** [CSenshi/Validator#88]
**Rule Name:** Accepted

**Rule Description:**
The field under validation must be 'yes', 'on', '1', or 'True'(true). This is useful for validating "Terms of Service" acceptance.

**Rule Usage Example:**
```python
reqs = {"data" : "True"}
rule = {"data" : "accepted"}
validate(reqs, rule) # True

reqs = {"data" : "False"}
rule = {"data" : "accepted"}
validate(reqs, rule) # False
```
----------------------------------------------------
**Before contributing please review [RULES.md](https://github.com/CSenshi/Validator/blob/master/RULES.md) (check for duplication), also check [CONTRIBUTING.md](https://github.com/CSenshi/Validator/blob/master/CONTRIBUTING.md) for more details :100:**

**Comment by Rogavactive** [comment]
I would like to work on this!
